apiVersion: v1
kind: Service
metadata:
  labels:
    app: airdrop-api
  name: airdrop-api
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8081
  selector:
    app: airdrop-api
  type: LoadBalancer
status:
  loadBalancer: {}